on:
  # So that PRs touching the same files as the push are updated
  push:
   branches: 
      - '**'
      
  # So that the `dirtyLabel` is removed if conflicts are resolve
  # We recommend `pull_request_target` so that github secrets are available.
  # In `pull_request` we wouldn't be able to change labels of fork PRs
  pull_request_target:
    types: [synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      
      - name: Sync labels
        uses: micnncim/action-label-syncer@v1.3.0
    
      - name: Check if PRs are dirty
      
        uses: eps1lon/actions-label-merge-conflict@v2.1.0
        with:
          dirtyLabel: "conflict"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has conflicts."
          commentOnClean: "Conflicts have been resolved."
